language: node_js
node_js:
- 'node'
- '7'
before_install:
- npm install -g npm codecov greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- travis_wait 60 npm run coverage
- codecov
after_script: greenkeeper-lockfile-upload
before_deploy:
- npm-prepublish --verbose --lax
deploy:
  provider: npm
  email: alanlu1023@gmail.com
  api_key: $NPM_TOKEN
  on:
    all_branches: true
    tags: true
    node: '7'
    repo: gnosis/gnosis-contracts
